# Generated by Django 4.2.5 on 2024-03-03 15:45

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module_1_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module_1_users.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Traveling_Story',
        ),
        migrations.DeleteModel(
            name='Ukrainian_Story',
        ),
        migrations.AddField(
            model_name='example',
            name='category',
            field=django_enum.fields.EnumCharField(choices=[('1', 'music'), ('2', 'war'), ('3', 'anime'), ('4', 'manga')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='example',
            name='dataset',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='example',
            name='result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=django_enum.fields.EnumCharField(choices=[('1', 'music'), ('2', 'war'), ('3', 'anime'), ('4', 'manga')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=django_enum.fields.EnumCharField(choices=[('1', 'music'), ('2', 'war'), ('3', 'anime'), ('4', 'manga')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('B', 'basic'), ('T', 'traveling'), ('U', 'ukrainian')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='example',
            name='tags',
            field=models.ManyToManyField(to='module_1_users.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='module_1_users.tag'),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(to='module_1_users.tag'),
        ),
    ]
