# Generated by Django 4.2.5 on 2024-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_1_users', '0002_tag_delete_category_delete_traveling_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.AddField(
            model_name='example',
            name='category',
            field=models.ManyToManyField(to='module_1_users.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='module_1_users.category'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(to='module_1_users.category'),
        ),
    ]
