# Generated by Django 4.2.5 on 2024-03-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1_users', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
