# Generated by Django 4.2.5 on 2024-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_1_users', '0006_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='life', max_length=250, unique=True),
        ),
    ]
