# Generated by Django 4.2.5 on 2024-04-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1_users', '0007_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='category',
            new_name='categories',
        ),
    ]
