# Generated by Django 4.2.5 on 2024-04-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_1_users', '0008_rename_category_story_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='category',
        ),
        migrations.RemoveField(
            model_name='example',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='story',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
