# Generated by Django 4.2.5 on 2024-04-15 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_2_story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desctription', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=100)),
                ('link_dithub', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(to='module_2_story.category')),
                ('tags', models.ManyToManyField(to='module_2_story.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.TextField(default='')),
                ('result', models.TextField(default='')),
                ('category', models.ManyToManyField(to='module_2_story.category')),
                ('tags', models.ManyToManyField(to='module_2_story.tag')),
            ],
        ),
    ]
