# Generated by Django 5.0.4 on 2024-05-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='example',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
