# Generated by Django 5.0.4 on 2024-05-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_rename_category_example_categories_example_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categories',
        ),
    ]
